/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.ManageCoursesResp;

import CourseCatalog.Course;
import CourseCatalog.CourseCatalog;
import CourseSchedule.CourseOffer;
import CourseSchedule.CourseSchedule;
import Department.Department;
import Faculty.FacultyProfile;
import University.University;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sabrina
 */
public class ManageCourseJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    University university;
    Department department;
    FacultyProfile facultyProfile;
    Course course;
    CourseCatalog courseCatalog;
    CourseOffer courseOffer;
    CourseSchedule courseSchedule;
    
    /**
     * Creates new form FacultyManageCourseJPanel
     */
    public ManageCourseJPanel(FacultyProfile fp, JPanel clp) {
        CardSequencePanel = clp;
        this.facultyProfile = fp;
        this.department = fp.getDepartment();
        initComponents();
        
        populateCourseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        lblCourses = new javax.swing.JLabel();
        lblManageCourses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        fieldSearch = new javax.swing.JTextField();
        btnViewCourse = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        lblCourses.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCourses.setText("Courses");

        lblManageCourses.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblManageCourses.setText("Manage Courses");

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Number", "Name", "Credits", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewCourse.setText("View Course");
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Back)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblManageCourses)
                .addGap(42, 42, 42)
                .addComponent(lblCourses)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnViewCourse)))
                .addGap(37, 37, 37)
                .addComponent(Back)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        //Search course based on course number
        if (!fieldSearch.getText().isBlank()) {
            String number = fieldSearch.getText();
            Course foundCourse = department.getCourseCatalog().getCourseByNumber(number);
            
            if (foundCourse != null) {
                ViewCourseJPanel vc = new ViewCourseJPanel(university, foundCourse, facultyProfile, CardSequencePanel);
                CardSequencePanel.add("ViewCourseJPanel", vc);
                CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
                layout.next(CardSequencePanel);
                fieldSearch.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Course not found. Please check course number and try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else JOptionPane.showMessageDialog(null, "Please enter a course number to view.", "Warning", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
        // TODO add your handling code here:
        //Select a course to view
        int selectedRow = tblCourses.getSelectedRow();
        if (selectedRow >=0) {
            Course selectedCourse = (Course) tblCourses.getValueAt(selectedRow, 0);
            ViewCourseJPanel vc = new ViewCourseJPanel(university, selectedCourse, facultyProfile, CardSequencePanel);
            CardSequencePanel.add("ViewCourseJPanel", vc);
            CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
            layout.next(CardSequencePanel);
        } else JOptionPane.showMessageDialog(null, "Please select a course from the list to view.", "Warning", JOptionPane.WARNING_MESSAGE);    
        
    }//GEN-LAST:event_btnViewCourseActionPerformed

    //Populate JTable with course details
    public void populateCourseTable() {
        //clears table rows
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);
        
        CourseCatalog cc = department.getCourseCatalog(); //will retrieve courses based on logged in faculty's department
        List<Course> courses = cc.getCourseList();
        
        for (Course c : courses) {
        Object[] row = new Object[4];
        row[0] = c;
        row[1] = c.getCourseName();
        row[2] = c.getCredits();
        row[3] = c.getCoursePrice();
        model.addRow(row);
    }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourses;
    private javax.swing.JLabel lblManageCourses;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
