/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.ManageCoursesResp;

import CourseCatalog.Course;
import CourseCatalog.CourseCatalog;
import CourseSchedule.CourseOffer;
import CourseSchedule.CourseSchedule;
import Department.Department;
import Faculty.FacultyProfile;
import University.University;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sabrina
 */
public class ManageCourseJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    University university;
    Department department;
    FacultyProfile facultyProfile;
    Course course;
    CourseCatalog courseCatalog;
    CourseOffer courseOffer;
    CourseSchedule courseSchedule;
    
    /**
     * Creates new form FacultyManageCourseJPanel
     */
    public ManageCourseJPanel(FacultyProfile fp, JPanel clp) {
        CardSequencePanel = clp;
        this.facultyProfile = fp;
        this.department = fp.getDepartment();
        initComponents();
        refreshCourseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        lblCourses = new javax.swing.JLabel();
        lblManageCourses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        fieldSearch = new javax.swing.JTextField();
        btnViewCourse = new javax.swing.JButton();

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        btnDeleteCourse.setText("Delete Course");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        lblCourses.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCourses.setText("Courses");

        lblManageCourses.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblManageCourses.setText("Manage Courses");

        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Number", "Name", "Credits", "Price"
            }
        ));
        CourseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CourseTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(CourseTable);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewCourse.setText("View Course");
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Back))))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblManageCourses)
                .addGap(42, 42, 42)
                .addComponent(lblCourses)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCourse)
                    .addComponent(btnDeleteCourse))
                .addGap(37, 37, 37)
                .addComponent(Back)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);

        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_BackActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
        /*
        int selectedRow = UserAccountTable.getSelectedRow();

        if (selectedRow >= 0) {

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected account?","Warning",dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                UserAccount selectedAccount = (UserAccount) UserAccountTable.getValueAt(selectedRow, 0);
                business.getUserAccountDirectory().deleteUserAccount(selectedAccount);
                refreshTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an account from the list to delete.", "Warning",JOptionPane.WARNING_MESSAGE);
        } */
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void CourseTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseTableMousePressed
        // Extracts the row (uaser account) in the table that is selected by the user
        /*
        int size = UserAccountTable.getRowCount();
        int selectedrow = UserAccountTable.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selecteduseraccount = (UserAccount) UserAccountTable.getValueAt(selectedrow, 0);
        if (selecteduseraccount == null) {
            return;

        } */
    }//GEN-LAST:event_CourseTableMousePressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        /*
        if (!fieldSearch.getText().isBlank()) {

            int studentID = Integer.parseInt(fieldSearch.getText());
            UserAccount foundAccount = business.getUserAccountDirectory().searchStudentAccount(studentID);

            if (foundAccount != null) {

                ViewStudentAccountJPanel viewStudentAccountJPanel = new ViewStudentAccountJPanel(business, business.getUserAccountDirectory(), foundAccount, CardSequencePanel);
                CardSequencePanel.add("viewStudentAccountJPanel", viewStudentAccountJPanel);
                CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
                layout.next(CardSequencePanel);
                fieldSearch.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Student NUID not found. Please ask student to create an account.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else JOptionPane.showMessageDialog(null, "Please enter a student NUID to view.", "Warning", JOptionPane.WARNING_MESSAGE);
*/
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
        // TODO add your handling code here:
        /*
        int selectedRow = UserAccountTable.getSelectedRow();
        ViewAdminAccountJPanel viewAdminAccountJPanel;
        ViewStudentAccountJPanel viewStudentAccountJPanel;
        ViewFacultyAccountJPanel viewFacultyAccountJPanel;

        if (selectedRow >= 0) {
            UserAccount selectedAccount = (UserAccount) UserAccountTable.getValueAt(selectedRow, 0);
            String role = selectedAccount.getRole();

            if (role.equals("Admin")) {
                viewAdminAccountJPanel = new ViewAdminAccountJPanel(business, business.getUserAccountDirectory(), selectedAccount, CardSequencePanel);
                CardSequencePanel.add("ViewAdminAccountJPanel", viewAdminAccountJPanel);
                CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
                layout.next(CardSequencePanel);
            } else if (role.equals("Faculty")) {
                viewFacultyAccountJPanel = new ViewFacultyAccountJPanel(business, business.getUserAccountDirectory(), selectedAccount, CardSequencePanel);
                CardSequencePanel.add("ViewFacultyAccountJPanel", viewFacultyAccountJPanel);
                CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
                layout.next(CardSequencePanel);
            } else if (role.equals("Student")) {
                viewStudentAccountJPanel = new ViewStudentAccountJPanel(business, business.getUserAccountDirectory(), selectedAccount, CardSequencePanel);
                CardSequencePanel.add("ViewStudentAccountJPanel", viewStudentAccountJPanel);
                CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
                layout.next(CardSequencePanel);
            }
        } else JOptionPane.showMessageDialog(null, "Please select an account from the list to view.", "Warning", JOptionPane.WARNING_MESSAGE);
*/
    }//GEN-LAST:event_btnViewCourseActionPerformed

    public void refreshCourseTable() {
        int rc = CourseTable.getRowCount();
        int i;
        for (i = rc - 1; i>=0; i--) {
            ((DefaultTableModel) CourseTable.getModel()).removeRow(i);
        }
        
        CourseCatalog cc = department.getCourseCatalog();
        List<Course> courses = cc.getCourseList();
        
        for (Course c : cc.getCourseList()) {
        Object[] row = new Object[4];
        row[0] = c;
        row[1] = c.getCourseName();
        row[2] = c.getCredits();
        row[3] = c.getCoursePrice();
        
        ((DefaultTableModel) CourseTable.getModel()).addRow(row);
    }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTable CourseTable;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourses;
    private javax.swing.JLabel lblManageCourses;
    // End of variables declaration//GEN-END:variables
}
