/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManageStudents;

import UserInterface.WorkAreas.AdminRole.ManageFaculty.*;
import Faculty.FacultyDirectory;
import Faculty.FacultyProfile;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.*;
import Persona.Person;
import Persona.PersonDirectory;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.*;
import University.University;
import Student.StudentDirectory;
import Student.StudentProfile;
import UserAccounts.UserAccount;
import UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vrmohanc
 */
public class ManageStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new manage persons form
     */
    JPanel CardSequencePanel;
    University university;
    StudentProfile selectedStudent;
    StudentDirectory sd;

    public ManageStudentJPanel(University uni, JPanel jp) {
        CardSequencePanel = jp;
        this.university = uni;
        
        initComponents();
        refreshTable();

    }

    public void refreshTable() {

        //clear table
        int rc = StudentTable.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) StudentTable.getModel()).removeRow(i);
        }

        sd = university.getStudentdirectory();
        
        
        for (StudentProfile sa : sd.getStudentlist()) {

            Object[] row = new Object[7];
            row[0] = sa;
            row[1] = sa.getPerson().getFirstName();
            row[2] = sa.getPerson().getLastName();
            row[3] = sa.getDepartment();
            row[4] = sa.getProgramEnrolled();
            row[5] = sa.getInstructionMode();
            row[6] = sa.getnUID();
            
            
            //get nUID for student accounts only
            //if (ua.getRole().equalsIgnoreCase("Student")) {
                //StudentProfile stu = (StudentProfile) ua.getAssociatedPersonProfile();
                //row[5] = stu.getnUID();
            //}
                                        
            ((DefaultTableModel) StudentTable.getModel()).addRow(row);
        }  
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        btnRemoveStudent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearchbyID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(30, 300, 80, 23);

        Next.setText("View/Edit >>");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        add(Next);
        Next.setBounds(470, 300, 110, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Student Details");
        add(jLabel1);
        jLabel1.setBounds(30, 90, 190, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Students");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Person ID", "First Name", "Last Name", "Department", "Program", "Mode", "NUID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudentTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(StudentTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 570, 130);

        btnRemoveStudent.setText("Remove Student");
        btnRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStudentActionPerformed(evt);
            }
        });
        add(btnRemoveStudent);
        btnRemoveStudent.setBounds(310, 300, 110, 23);

        jLabel3.setText("Search by ID");
        add(jLabel3);
        jLabel3.setBounds(30, 360, 100, 17);
        add(txtSearchbyID);
        txtSearchbyID.setBounds(150, 360, 200, 23);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(380, 360, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
 //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        //if(selecteduseraccount==null) return;
        int row = StudentTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        selectedStudent = (StudentProfile) StudentTable.getValueAt(row, 0);
        AdministerStudentJPanel mppd = new AdministerStudentJPanel(selectedStudent, CardSequencePanel, university);
        CardSequencePanel.add(mppd);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_NextActionPerformed

    private void StudentTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMousePressed
        // Extracts the row (uaser account) in the table that is selected by the user
        //int size = UserAccountTable.getRowCount();
        //int selectedrow = UserAccountTable.getSelectionModel().getLeadSelectionIndex();

        //if (selectedrow < 0 || selectedrow > size - 1) {
         //   return;
        //}
        //selecteduseraccount = (UserAccount) UserAccountTable.getValueAt(selectedrow, 0);
    if (selectedStudent == null) {
            return;        
    }//GEN-LAST:event_StudentTableMousePressed
    
    }
    
    private void btnRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStudentActionPerformed
        // TODO add your handling code here:
        //remove selected User account
        int row = StudentTable.getSelectedRow();
     
        //error handling
        if (row >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete selected faculty?", "Warning", JOptionPane.WARNING_MESSAGE);
            
            if (dialogResult == JOptionPane.YES_OPTION) {
                selectedStudent = (StudentProfile) StudentTable.getValueAt(row, 0);
                university.getStudentdirectory().removeStudentProfile(selectedStudent);
               
                refreshTable();
            }
            
        } else {
            JOptionPane.showMessageDialog(this,"Select a row to delete", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRemoveStudentActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        //search student by person ID
        try {
            StudentProfile student = sd.findStudent(txtSearchbyID.getText());
            //display search results
            refreshSearchResults(student);
        } catch (NullPointerException e){
            JOptionPane.showMessageDialog(this,"student with person ID not found", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void refreshSearchResults(StudentProfile student) {
        //clear table
        int rc = StudentTable.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) StudentTable.getModel()).removeRow(i);
        }

        
    
            Object[] row = new Object[7];
            row[0] = student;
            row[1] = student.getPerson().getFirstName();
            row[2] = student.getPerson().getLastName();
            row[3] = student.getDepartment().getName();
            row[4] = student.getProgramEnrolled();
            row[5] = student.getInstructionMode();
            row[6] = student.getnUID();
            //display nUID for found student
            //if (ua.getRole().equalsIgnoreCase("Student")) {
            //    StudentProfile stu = (StudentProfile) ua.getAssociatedPersonProfile();
            //    row[5] = stu.getnUID();
            //}                           
            ((DefaultTableModel) StudentTable.getModel()).addRow(row);
          
    }
    
    private UserAccount searchStudentbyNUID(String searchID) {
        
        StudentProfile stu = university.getStudentDirectory().findStudentByNUID(searchID);
        
        for (UserAccount ua: university.getUserAccountDirectory().getUserAccountList()) {
            if (ua.isProfileMatch(stu)) {
                return ua;
            }
        }
        
        return null;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Next;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton btnRemoveStudent;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearchbyID;
    // End of variables declaration//GEN-END:variables
}

