/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole.Transcript;

import CourseSchedule.CourseLoad;
import CourseSchedule.SeatAssignment;
import Student.StudentProfile;
import Student.Transcript;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author csong
 */
public class TranscriptJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TranscriptJPanel
     */
    
    StudentProfile student;
    JPanel CardSequencePanel;
    Transcript transcript;
    HashMap<String, CourseLoad> masterCourseLoad;
    public TranscriptJPanel(StudentProfile s, JPanel csp) {
        
        initComponents();
        student = s;
        CardSequencePanel = csp;
        transcript = student.getTranscript();
        populateTranscript();
        
        // get data to fields
        fieldGPA.setText(String.valueOf(transcript.getCumulativeGPA()));
        fieldCredits.setText(String.valueOf(transcript.getStudentTotalCreditHours()));
        fieldQP.setText(String.valueOf(transcript.getStudentTotalScore()));
        
        // disable editing
        fieldGPA.setEditable(false);
        fieldCredits.setEditable(false);
        fieldQP.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTranscript = new javax.swing.JTable();
        lblGPA = new javax.swing.JLabel();
        fieldGPA = new javax.swing.JTextField();
        lblCredits = new javax.swing.JLabel();
        fieldCredits = new javax.swing.JTextField();
        lblQP = new javax.swing.JLabel();
        fieldQP = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Transcript");

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        tblTranscript.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        tblTranscript.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Semester", "Number", "Name", "Faculty", "Credit Hour", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTranscript);
        if (tblTranscript.getColumnModel().getColumnCount() > 0) {
            tblTranscript.getColumnModel().getColumn(2).setMinWidth(200);
        }

        lblGPA.setText("Cumulative GPA:");

        fieldGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldGPAActionPerformed(evt);
            }
        });

        lblCredits.setText("Cumulative Credit Hours:");

        fieldCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCreditsActionPerformed(evt);
            }
        });

        lblQP.setText("Cumulative Quality Points:");

        fieldQP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGPA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCredits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(599, 599, 599)
                        .addComponent(lblQP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldQP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Back)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblGPA)
                    .addComponent(fieldGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredits)
                    .addComponent(fieldCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQP)
                    .addComponent(fieldQP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Back)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void populateTranscript() {
        DefaultTableModel model = (DefaultTableModel) tblTranscript.getModel();
        model.setRowCount(0);
        
        // get the master course load
        masterCourseLoad = transcript.getMasterCourseloadlist();
        
        // iterate over the master course load hash map
        for(Map.Entry<String, CourseLoad> entry: masterCourseLoad.entrySet()) {
            String semester = entry.getKey();
            CourseLoad cl = entry.getValue();
            
            for (SeatAssignment sa: cl.getSeatAssignments()) {
                Object[] row = new Object[6];
                row[0] = semester;
                row[1] = sa.getCourseOffer().getCourseNumber();
                row[2] = sa;
                row[3] = sa.getCourseOffer().getFacultyProfile().getPersonFullName();
                row[4] = sa.getCreditHours();
                // label grade with "in progress" if not completed/ not graded
                if (sa.isCompleted()) {
                    row[5] = sa.getGrade();
                } else {
                    row[5] = "In progress";
                }
                
                model.addRow(row);
            }
        }
        
    }
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void fieldGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldGPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldGPAActionPerformed

    private void fieldCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCreditsActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void fieldQPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField fieldCredits;
    private javax.swing.JTextField fieldGPA;
    private javax.swing.JTextField fieldQP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblQP;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTranscript;
    // End of variables declaration//GEN-END:variables


}
