/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package University;

import Department.Department;
import Employee.EmployeeProfile;
import Faculty.FacultyProfile;
import Profile.Profile;
import Student.StudentProfile;

import UserAccounts.UserAccount;
import UserAccounts.UserAccountDirectory;

import UserInterface.WorkAreas.AdminRole.AdminRoleWorkAreaJPanel;
import UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel;
import UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class ProfileWorkAreaMainFrame extends javax.swing.JFrame {

    University university;
    Department department;
    UserAccount user;

    /**
     * Creates new form PricingMainFrame
     */

    public ProfileWorkAreaMainFrame() {
        initComponents();
        university = ConfigureUniversity.initialize();
        
        // set logout button to be invisible
        btnLogout.setVisible(false);
    }

    public void insert(JPanel jpanel) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitHomeArea = new javax.swing.JSplitPane();
        actionsidejpanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnSignUpStudent = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        CardSequencePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actionsidejpanel.setBackground(new java.awt.Color(0, 153, 153));
        actionsidejpanel.setMinimumSize(new java.awt.Dimension(200, 200));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        lblUsername.setText("User Name");

        UserNameTextField.setText("admin");

        PasswordTextField.setText("****");
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        lblPassword.setText("Password");

        btnSignUpStudent.setText("Sign Up As Student");
        btnSignUpStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpStudentActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionsidejpanelLayout = new javax.swing.GroupLayout(actionsidejpanel);
        actionsidejpanel.setLayout(actionsidejpanelLayout);
        actionsidejpanelLayout.setHorizontalGroup(
            actionsidejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionsidejpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignUpStudent)
                .addGap(20, 20, 20))
            .addGroup(actionsidejpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(actionsidejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(lblUsername)
                    .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        actionsidejpanelLayout.setVerticalGroup(
            actionsidejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsidejpanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblUsername)
                .addGap(4, 4, 4)
                .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(btnSignUpStudent)
                .addGap(58, 58, 58)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        SplitHomeArea.setLeftComponent(actionsidejpanel);

        CardSequencePanel.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("Education Going Digital .... Info 5100 ");
        CardSequencePanel.add(jLabel3, "card2");

        SplitHomeArea.setRightComponent(CardSequencePanel);

        getContentPane().add(SplitHomeArea, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        //      WorkAreaJPanel ura = new WorkAreaJPanel(workareajpanl);

        String un = UserNameTextField.getText();
        String pw = PasswordTextField.getText();

        UserAccountDirectory uad = university.getUserAccountDirectory();
        UserAccount useraccount = uad.AuthenticateUser(un, pw);
        
        if (useraccount == null) {
            JOptionPane.showMessageDialog(null, "User name or password are incorrect. Please retry", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        user = useraccount;
        StudentWorkAreaJPanel studentworkareajpanel;
        FacultyWorkAreaJPanel facultyworkarea;
        AdminRoleWorkAreaJPanel adminworkarea;
        String r = useraccount.getRole();
        //System.out.println(r);
        Profile profile = useraccount.getAssociatedPersonProfile();
        //System.out.println(profile);


        if (profile instanceof EmployeeProfile) {
                
            //update last activity at the user login
            user.setLastActivity(LocalDateTime.now());
            
            adminworkarea = new AdminRoleWorkAreaJPanel(university, CardSequencePanel, user);
            CardSequencePanel.removeAll();
            CardSequencePanel.add("Admin", adminworkarea);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        }
        

        if (profile instanceof StudentProfile) {
            
            //update last activity at the user login
            user.setLastActivity(LocalDateTime.now());
            
            StudentProfile spp = (StudentProfile) profile;
            studentworkareajpanel = new StudentWorkAreaJPanel(university, spp, CardSequencePanel);
            CardSequencePanel.removeAll();
            CardSequencePanel.add("student", studentworkareajpanel);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        }


         if (profile instanceof FacultyProfile) {
             
            //update last activity at the user login
            user.setLastActivity(LocalDateTime.now());
            FacultyProfile fp = (FacultyProfile) profile;
            Department facultydept = fp.getDepartment(); //retrieve department from faculty profile during login
            facultyworkarea = new FacultyWorkAreaJPanel(university, CardSequencePanel, fp, user);
            CardSequencePanel.removeAll();
            CardSequencePanel.add("faculty", facultyworkarea);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        }
         
         // change sidebar visibility
         lblUsername.setVisible(false);
         lblPassword.setVisible(false);
         btnLogin.setVisible(false);
         UserNameTextField.setVisible(false);
         PasswordTextField.setVisible(false);
         btnSignUpStudent.setVisible(false);
         btnLogout.setVisible(true);

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void btnSignUpStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpStudentActionPerformed
        // TODO add your handling code here:
        
        //Open sign up student form
        /*
        StudentSignUpJPanel studentsignup = new StudentSignUpJPanel(CardSequencePanel, university);
            //CardSequencePanel.removeAll();
            CardSequencePanel.add("student sign up", studentsignup);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        */
        
        // change sidebar visibility
//         lblUsername.setVisible(false);
//         lblPassword.setVisible(false);
//         btnLogin.setVisible(false);
//         UserNameTextField.setVisible(false);
//         PasswordTextField.setVisible(false);
//         btnSignUpStudent.setVisible(false);
//         btnLogout.setVisible(true);
        
    }//GEN-LAST:event_btnSignUpStudentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // change sidebar visibility
         lblUsername.setVisible(true);
         lblPassword.setVisible(true);
         btnLogin.setVisible(true);
         UserNameTextField.setVisible(true);
         PasswordTextField.setVisible(true);
         btnSignUpStudent.setVisible(true);
         btnLogout.setVisible(false);
         
         // clear and refresh card sequence
         CardSequencePanel.removeAll();
         CardSequencePanel.revalidate();
         CardSequencePanel.repaint();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileWorkAreaMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileWorkAreaMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileWorkAreaMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileWorkAreaMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileWorkAreaMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequencePanel;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JSplitPane SplitHomeArea;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JPanel actionsidejpanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSignUpStudent;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
