/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole.CourseWork;

import CourseSchedule.SeatAssignment;
import UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import java.awt.CardLayout;
import java.util.Stack;
import javax.swing.JPanel;

/**
 *
 * @author csong
 */
public class ViewCourseWorkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCourseWorkJPanel
     */
    SeatAssignment sa;
    JPanel CardSequencePanel;
    StudentWorkAreaJPanel swajp;
    public ViewCourseWorkJPanel(SeatAssignment sa, JPanel csp, StudentWorkAreaJPanel swajp) {
        initComponents();
        this.sa = sa;
        CardSequencePanel = csp;
        this.swajp = swajp;
        
        populateFields();
    }
    
    private void populateFields() {
        fieldCourseNumber.setText(sa.getAssociatedCourse().getCourseNumber());
        fieldName.setText(sa.getAssociatedCourse().getCourseName());
        fieldFaculty.setText(sa.getCourseOffer().getFacultyProfile().getPersonFullName());
        fieldCreditHours.setText(String.valueOf(sa.getCreditHours()));
        
        boolean status = sa.isCompleted();
        if (status) {
            fieldStatus.setText("Completed");
            fieldGrade.setText(String.valueOf(sa.getGrade()));
        } else {
            fieldStatus.setText("In Progress");
            fieldGrade.setText("N/A");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblFaculty = new javax.swing.JLabel();
        fieldFaculty = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblCreditHours = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        fieldCourseNumber = new javax.swing.JTextField();
        fieldCreditHours = new javax.swing.JTextField();
        Back2 = new javax.swing.JButton();
        lblGrade = new javax.swing.JLabel();
        fieldGrade = new javax.swing.JTextField();
        lblSatus = new javax.swing.JLabel();
        fieldStatus = new javax.swing.JTextField();
        btnAssignment = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblName.setText("Name:");

        lblFaculty.setText("Faculty:");

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Course Work");

        lblCreditHours.setText("Credit Hours:");

        lblNumber.setText("Course Number:");

        fieldCourseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCourseNumberActionPerformed(evt);
            }
        });

        Back2.setText("<< Back");
        Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back2ActionPerformed(evt);
            }
        });

        lblGrade.setText("Grade:");

        lblSatus.setText("Status:");

        btnAssignment.setText("Submit Assignments");
        btnAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAssignment))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNumber)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGrade)
                                        .addComponent(lblName)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                        .addComponent(fieldCourseNumber)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFaculty, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCreditHours, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSatus, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCreditHours, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(fieldFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(fieldStatus)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Back2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber)
                    .addComponent(lblFaculty)
                    .addComponent(fieldFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(lblCreditHours)
                    .addComponent(fieldCreditHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrade)
                    .addComponent(fieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSatus)
                    .addComponent(fieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(btnAssignment)
                .addGap(41, 41, 41)
                .addComponent(Back2)
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back2ActionPerformed
        // TODO add your handling code here:
        Stack<String> historyStack = swajp.getHistoryStack();
        JPanel csp = swajp.getCardSequencePanel();
        if (!historyStack.empty()) {
            String previousKey = historyStack.pop();
            CardLayout layout = (CardLayout) csp.getLayout();
            layout.show(csp, previousKey);
            csp.remove(this);
        }else {
            // go to student main frame
            CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
            layout.show(CardSequencePanel, "StudentWorkAreaJPanel");
        }
        
        //CardSequencePanel.remove(this);
        //((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_Back2ActionPerformed

    private void fieldCourseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCourseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCourseNumberActionPerformed

    private void btnAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentActionPerformed
        swajp.getHistoryStack().push("ViewCourseWorkJPanel");
        
        SubmitAssignmentJPanel sajp = new SubmitAssignmentJPanel(sa, CardSequencePanel, swajp);
        CardSequencePanel.add("SubmitAssignmentJPanel", sajp);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnAssignmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back2;
    private javax.swing.JButton btnAssignment;
    private javax.swing.JTextField fieldCourseNumber;
    private javax.swing.JTextField fieldCreditHours;
    private javax.swing.JTextField fieldFaculty;
    private javax.swing.JTextField fieldGrade;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldStatus;
    private javax.swing.JLabel lblCreditHours;
    private javax.swing.JLabel lblFaculty;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblSatus;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
