/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.ManageStudentsResp;

import Student.StudentProfile;
import University.University;
import UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sabrina
 */
public class ManageStudentProfileJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    StudentProfile studentProfile;
    University university;
    
    /**
     * Creates new form ManageStudentProfileJPanel
     */
    public ManageStudentProfileJPanel(StudentProfile sp, JPanel clp) {
        CardSequencePanel = clp;
        this.studentProfile = sp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        lblCourses = new javax.swing.JLabel();
        lblManageCourses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        fieldSearch = new javax.swing.JTextField();
        btnViewStudent = new javax.swing.JButton();

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        lblCourses.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCourses.setText("Courses");

        lblManageCourses.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblManageCourses.setText("Manage Students");

        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUID", "First Name", "Last Name", "Hobbies", "Interests"
            }
        ));
        CourseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CourseTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(CourseTable);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewStudent.setText("View Student Details");
        btnViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnViewStudent))
                            .addComponent(Back))))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblManageCourses)
                .addGap(42, 42, 42)
                .addComponent(lblCourses)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewStudent))
                .addGap(37, 37, 37)
                .addComponent(Back)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);

        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_BackActionPerformed

    private void CourseTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseTableMousePressed
        // Extracts the row (uaser account) in the table that is selected by the user
        /*
        int size = UserAccountTable.getRowCount();
        int selectedrow = UserAccountTable.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selecteduseraccount = (UserAccount) UserAccountTable.getValueAt(selectedrow, 0);
        if (selecteduseraccount == null) {
            return;

        } */
    }//GEN-LAST:event_CourseTableMousePressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (!fieldSearch.getText().isBlank()) {
            
            String nUID = fieldSearch.getText();
            StudentProfile foundStudent = university.getStudentDirectory().findStudentByNUID(nUID);
            
            if (foundStudent != null) {
                
                ViewStudentProfileJPanel viewStudentProfileJPanel = new ViewStudentProfileJPanel(university, university.getStudentDirectory(), foundStudent, CardSequencePanel);
                CardSequencePanel.add("viewStudentProfileJPanel", viewStudentProfileJPanel);
                CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
                layout.next(CardSequencePanel);
                fieldSearch.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Student not found. Please check student NUID and try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else JOptionPane.showMessageDialog(null, "Please enter a student NUID to view.", "Warning", JOptionPane.WARNING_MESSAGE);        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentActionPerformed
        // TODO add your handling code here:
        /*
        int selectedRow = CourseTable.getSelectedRow();
        if (selectedRow >=0) {
            Course selectedCourse = (Course) CourseTable.getValueAt(selectedRow, 0);
            ViewCourseJPanel vc = new ViewCourseJPanel(university, courseCatalog, selectedCourse, CardSequencePanel);
            CardSequencePanel.add("ViewCourseJPanel", vc);
            CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
            layout.next(CardSequencePanel);
        } else JOptionPane.showMessageDialog(null, "Please select a course from the list to view.", "Warning", JOptionPane.WARNING_MESSAGE);
        */
    }//GEN-LAST:event_btnViewStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTable CourseTable;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewStudent;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourses;
    private javax.swing.JLabel lblManageCourses;
    // End of variables declaration//GEN-END:variables
}
