/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.ManageStudentsResp;

import Student.StudentDirectory;
import Student.StudentProfile;
import University.University;
import javax.swing.JPanel;

/**
 *
 * @author Sabrina
 */
public class ViewStudentProfileJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    University university;
    //Department department;
    StudentDirectory studentDirectory;
    StudentProfile studentProfile;
    //Course course;
    //CourseCatalog courseCatalog;
    
    /**
     * Creates new form ViewStudentProfileJPanel
     */
    public ViewStudentProfileJPanel(University u, StudentDirectory sd, StudentProfile sp, JPanel clp) {
        university = u;
        this.studentDirectory = sd;
        this.studentProfile = sp;
        this.CardSequencePanel = clp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMyProfile = new javax.swing.JLabel();

        lblMyProfile.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblMyProfile.setText("Student Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblMyProfile)
                .addContainerGap(423, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMyProfile;
    // End of variables declaration//GEN-END:variables
}
