/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.ManageStudentsResp;

import Student.StudentDirectory;
import Student.StudentProfile;
import University.University;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sabrina
 */
public class ViewStudentProfileJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    University university;
    StudentDirectory studentDirectory;
    StudentProfile selectedStudent;
    
    /**
     * Creates new form ViewStudentProfileJPanel
     */
    public ViewStudentProfileJPanel(University u, StudentDirectory sd, StudentProfile sp, JPanel clp) {
        university = u;
        this.studentDirectory = sd;
        this.selectedStudent = sp;
        this.CardSequencePanel = clp;
        initComponents();
        
        fieldPersonID.setText(this.selectedStudent.getPerson().getId());
        fieldNUID.setText(this.selectedStudent.getnUID());
        fieldFirstName.setText(this.selectedStudent.getPerson().getFirstName());
        fieldLastName.setText(this.selectedStudent.getPerson().getLastName());
        
        refreshStudentDetailTable(sp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        lblManageCourses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHobbyInterest = new javax.swing.JTable();
        btnViewStudent = new javax.swing.JButton();
        lblNUID = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        lblPersonID = new javax.swing.JLabel();
        fieldPersonID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        lblManageCourses.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblManageCourses.setText("Students Details");

        tblHobbyInterest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Hobbies", "Interests"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHobbyInterest);

        btnViewStudent.setText("View Student Courses");
        btnViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentActionPerformed(evt);
            }
        });

        lblNUID.setText("NUID:");

        fieldNUID.setEditable(false);

        lblLastName.setText("Last Name:");

        lblFirstName.setText("First Name:");

        fieldFirstName.setEditable(false);

        fieldLastName.setEditable(false);

        lblPersonID.setText("Person ID:");

        fieldPersonID.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNUID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPersonID, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldNUID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Back)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewStudent))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblManageCourses)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPersonID)
                            .addComponent(fieldPersonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNUID)
                            .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewStudent)
                            .addComponent(Back)))
                    .addComponent(lblFirstName))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void btnViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentActionPerformed
        // TODO add your handling code here:
        
        //Check if student courseload is null
        if (selectedStudent.getTranscript() == null) {
        //if student courseload is null, pop up an error message
            JOptionPane.showMessageDialog(null, "No courses were found for this student. Please ask student to enroll in courses.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            ViewStudentAcademicJPanel viewStudentAcademicJPanel = new ViewStudentAcademicJPanel(university, university.getStudentDirectory(), selectedStudent, CardSequencePanel);
            CardSequencePanel.add("ViewStudentAcademicJPanel", viewStudentAcademicJPanel);
            CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
            layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnViewStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnViewStudent;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldPersonID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblManageCourses;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblPersonID;
    private javax.swing.JTable tblHobbyInterest;
    // End of variables declaration//GEN-END:variables

    public void refreshStudentDetailTable(StudentProfile selectedStudent) {
        
        DefaultTableModel model = (DefaultTableModel) tblHobbyInterest.getModel();
        model.setRowCount(0);
        
        //if selected student is not null, then get hobbies and interests from studentProfile
        if (selectedStudent != null) {
            ArrayList<String> hobbies = selectedStudent.getHobbies();
            ArrayList<String> interests = selectedStudent.getInterests();

        // Display hobby and interests in separate rows
            int maxRows = Math.max(hobbies.size(), interests.size()); //check which list is longer
            for (int i = 0; i < maxRows; i++) { //loops through the rows based on hobbies/interests list
                Object[] row = new Object[2];
                row[0] = (i < hobbies.size()) ? hobbies.get(i) : ""; //add to row i if hobby is found, otherwise return blank
                row[1] = (i < interests.size()) ? interests.get(i) : ""; //add to row i if interest is found, otherwise return blank
                model.addRow(row);
            }
        }    
    }
}
