/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;




import Student.StudentProfile;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author csong
 */
public class StudentViewProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserProfileJPanel
     */
    JPanel CardSequencePanel;
    StudentProfile student;
    
    public StudentViewProfileJPanel(StudentProfile s, JPanel cjp) {
        initComponents();
        
        CardSequencePanel = cjp;
        student = s;
        
        // get profile's information
        String firstname = student.getPerson().getFirstName();
        String lastname = student.getPerson().getLastName();
        String NUID = student.getnUID();
        String department = student.getDepartment().getName();
        String admittedTerm = student.getTermAdmittedFirst();
        String program = student.getProgramEnrolled();
                
        // set the field
        fieldName.setText(firstname + " " + lastname);
        fieldAdmittedTerm.setText(admittedTerm);
        fieldDepartment.setText(department);
        fieldProgram.setText(program);
        fieldNUID.setText(NUID);
        
        fieldName.setEditable(false);
        fieldAdmittedTerm.setEditable(false);
        fieldDepartment.setEditable(false);
        fieldProgram.setEditable(false);
        fieldNUID.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldName = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAdmittedTerm = new javax.swing.JLabel();
        fieldAdmittedTerm = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        lblProgram = new javax.swing.JLabel();
        fieldDepartment = new javax.swing.JTextField();
        fieldProgram = new javax.swing.JTextField();
        lblNUID = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Student Profile");

        lblName.setText("Name:");

        lblAdmittedTerm.setText("Admitted Term:");

        lblDepartment.setText("Department:");

        lblProgram.setText("Program:");

        lblNUID.setText("NUID:");

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNUID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProgram, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDepartment, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAdmittedTerm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldProgram, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(fieldNUID)
                            .addComponent(fieldDepartment)
                            .addComponent(fieldAdmittedTerm)
                            .addComponent(fieldName))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Back)
                .addGap(39, 514, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTitle)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmittedTerm)
                    .addComponent(fieldAdmittedTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(fieldDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgram)
                    .addComponent(fieldProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNUID)
                    .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(Back)
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField fieldAdmittedTerm;
    private javax.swing.JTextField fieldDepartment;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldProgram;
    private javax.swing.JLabel lblAdmittedTerm;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
