/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import University.University;
import UserAccounts.UserAccount;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author vrmohanc
 */
public class AdminMyProfileJPanel extends javax.swing.JPanel {
    
    
    /**
     * Creates new form AdminMyProfileJPanel
     */
    JPanel CardSequencePanel;
    University university;
    UserAccount useraccount;
    
    public AdminMyProfileJPanel(JPanel CardSequencePanel, University university, UserAccount useraccount) {
        
        this.CardSequencePanel = CardSequencePanel;
        this.university = university;
        this.useraccount = useraccount;
        initComponents();
        
        String userName = useraccount.getUsername();
        String password = useraccount.getPassword();
        String personID = useraccount.getPersonId();
        
        txtUserName.setText(userName);
        txtPswd.setText(password);
        txtPersonID.setText(personID);
        txtPersonID.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPswd = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        txtPersonID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(50, 30, 76, 23);

        lblUserName.setText("User Name");
        add(lblUserName);
        lblUserName.setBounds(120, 90, 65, 17);
        add(txtUserName);
        txtUserName.setBounds(250, 90, 180, 23);

        lblPassword.setText("Password");
        add(lblPassword);
        lblPassword.setBounds(120, 150, 58, 17);
        add(txtPswd);
        txtPswd.setBounds(250, 150, 180, 23);

        lblFullName.setText("Person ID");
        add(lblFullName);
        lblFullName.setBounds(120, 220, 80, 17);
        add(txtPersonID);
        txtPersonID.setBounds(250, 220, 180, 23);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(250, 280, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        //back to Admin work area
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //save details
        useraccount.setUsername(txtUserName.getText());
        useraccount.setPassword(txtPswd.getText());
        JOptionPane.showMessageDialog(this, "User details updated successfully ",
                    "Warning", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtPersonID;
    private javax.swing.JTextField txtPswd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
